services:
  mysql:
    image: mysql:8.0
    container_name: tis-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 71718902
      MYSQL_DATABASE: db_portafolios_tis
      MYSQL_USER: teamsys
      MYSQL_PASSWORD: teamsys123
    ports:
      - "3307:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Tis-back
    container_name: tis-back
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      # We target the Coolify database server IP and public port here
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: db_portafolios_tis
      DB_USER: teamsys
      DB_PASSWORD: teamsys123

      BREVO_KEY: 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
      BREVO_EMAIL: 202103868@est.umss.edu
      URL_FRONT: http://localhost:5173
      JWT_SECRET: una_clave_secreta_muy_larga_y_segura_para_deploy
      PORT: 8081

  frontend:
    build:
      context: ./Tis-front-
      args:
        VITE_API_URL:  http://localhost:8081
    container_name: tis-front
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend

volumes:
  mysql_data:
