spring.application.name=Tis-back

# Importar variables locales para desarrollo
spring.config.import=optional:file:env.properties

# Datos de conexion usando variables de entorno
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_portafolios_tis}?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto dinamico para el servidor
server.port=${PORT:8081}

# Configuracion de servicios externos
brevo.api.key=${BREVO_KEY}
brevo.email.from=${BREVO_EMAIL}
url.front=${URL_FRONT}

# Seguridad JWT
jwt.secret=${JWT_SECRET}